services:
  - type: web
    name: pixel-love-api
    runtime: node
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg python3 python3-pip
      pip3 install yt-dlp
      npm install
      npm run build
    startCommand: node dist/main.js
    plan: starter
    envVars:
      - key: IS_WORKER
        value: "false"
      - key: NODE_ENV
        value: production

  - type: worker
    name: pixel-love-worker
    runtime: node
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg python3 python3-pip
      pip3 install yt-dlp
      npm install
      npm run build
    startCommand: node dist/main.js
    plan: starter
    envVars:
      - key: IS_WORKER
        value: "true"
      - key: NODE_ENV
        value: production
